# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c4b43eb51d6318e8af3400b6b5a7a264"
name = "Oban All-in-one Offers"
application_url = "https://all-in-one-promotions-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  uri = "https://all-in-one-promotions.onrender.com/api/webhooks/shop/update"
  topics = [ "shop/update" ]

  [[webhooks.subscriptions]]
  uri = "https://all-in-one-promotions.onrender.com/api/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://all-in-one-promotions.onrender.com/api/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://all-in-one-promotions.onrender.com/api/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://all-in-one-promotions.onrender.com/api/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "https://all-in-one-promotions.onrender.com/api/webhooks/products/delete"
  topics = [ "products/delete" ]

  [[webhooks.subscriptions]]
  uri = "https://all-in-one-promotions.onrender.com/api/webhooks/products/update"
  topics = [ "products/update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_discounts,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://all-in-one-promotions-production.up.railway.app/auth/callback",
  "https://all-in-one-promotions-production.up.railway.app/auth/shopify/callback"
]

[app_proxy]
url = "https://all-in-one-promotions-production.up.railway.app"
subpath = "promotions"
prefix = "apps"

[pos]
embedded = false
